# Site
repository: sproogen/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Gwak Miso
title: Portfolio
email: gkmiso@naver.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: gkmiso

# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: 소개
about_profile_image: images/profile.png
about_content: | 
  안녕하세요. 함께 소통할 인재, <mark>곽미소</mark>입니다.<br/>
  <br/>
  개발자로서 **사용자 경험**을 향상하며, **가치를 전달**하는 것이 제 꿈입니다. 사용자 중심의 서비스 제공을 통해 **기술**, **디자인**, **협업**의 중요성을 명확히 이해하고, 이를 구현하는 과정에 기여하고자 합니다.<br/>
  <br/>
  개발자로 일하면서, 발전하는 기술 트랜드에 대해 관심을 가지고 학습하는 마인드를 가지며 성장하고 회사의 비전을 실현하는데 이바지하겠습니다.<br/>
  <br/>
  팀원들과의 원활한 협업을 통해 프로젝트의 성공을 이루어 내기 위해 노력하며, 팀의 목표를 함께 공유하고 효율적으로 협력합니다. 팀원들과 함께 더 나은 제품을 만들어내는 것이 제 목표 중 하나입니다.<br/>
  <br/>
  서비스를 개발하는 개발자로서의 역할을 수행하면서, 혁신적이고 사용자 중심의 서비스를 제공하는 데 동참하고, 회사와 함께 성장하고자 합니다. 이 기회를 통해 더 나은 미래를 함께 만들어 나가기를 기대합니다.<br/>
  
  - [Tistory](https://gkmiso.tistory.com)
  - [Github](https://github.com/gkmiso)

content:
  - title: 학력
    layout: list
    content:
      - layout: left
        caption: "2020.02.14 졸업"
        description: | 
          - **○○○○○○대학교**
          - 컴퓨터공학부 컴퓨터공학과

  - title: 경력
    layout: list
    content:
      - layout: left
        caption: "2020.08.12 - 2022.09.30"
        description: | 
          - **(주)○○○○○○○**
          - Data Service / 사원
            - <mark>Excel</mark>
            - 데이터 리서치 및 정제
            - 데이터 통계 및 분석
            - 고객사 DB 운영/대행
            - 관리방안 도출 및 Insight 도출
            
          - 성과
            - 2021년 전체 부서 평균 73% 중 **개인 성과로 93% 달성**
            - 업무 정확도와 속도 향상으로 팀의 성과에 긍정적인 영향을 미침

  - title: 교육 이수
    layout: list
    content:
      - layout: left
        caption: "2022.12.15 - 2023.06.08 (120일 / 총 960시간)"
        description: | 
          - **소프트웨어 엔지니어링 부트캠프 (프론트엔드)**
            - [코드스테이츠](https://www.codestates.com/)
          - 교육
              - [커리큘럼](https://www.codestates.com/help/article/4465186680217/)
              - <mark>HTML</mark> <mark>CSS</mark> <mark>JavaScript</mark> <mark>React</mark> <mark>Figma</mark>
              - 약 4개월간 18명의 동료와 랜덤 페어 프로그래밍
          - stackoverflow Clone Coding 프로젝트 (2023.04.11 - 2023.04.27)
              - [stackoverflow](https://stackoverflow.co/) 홈페이지 클론코딩 (회원가입, 로그인, 마이페이지, 질문페이지)
          - Lumian 프로젝트 (2023.04.28 - 2023.05.25)
              - 해당 웹사이트는 위버스에서 영감을 받아 만들어졌습니다. [Lumian](http://lumian-project.s3-website.ap-northeast-2.amazonaws.com/)은 아티스트와 팬 간의 경계를 허물고, 함께 소통할 수 있는 공간입니다. 소셜 네트워크와 같은 커뮤니티 기능을 통해 팬들은 아티스트와 쉽게 대화를 나눌 수 있으며, 아티스트 노래 추천 기능을 제공하고 있어서 팬들은 아티스트가 추천하는 곡을 들을 수 있습니다.
              - 사용 기술 스택(front-end) : <mark>JavaScript</mark> <mark>React</mark> <mark>React-Router</mark> <mark>Redux-ToolKit</mark> <mark>Styled-Components</mark> <mark>Axios</mark> <mark>ESLint</mark> <mark>Prettier</mark> <mark>Figma</mark>
              - 팀 구성 : FE 3명, BE 2명
              - 담당(팀원) : 초기 뮤직 페이지 구현, 프로필 페이지 기능 및 페이지 구현, 소개 페이지 기능 및 페이지 구현

  - title: 자격증
    layout: list
    content:
      - layout: left
        caption: "2024.00.00"
        description: | 
          - **정보처리기사**
              - 한국산업인력공단
      - layout: left
        caption: "2023.12.29"
        description: | 
          - **리눅스마스터 2급**
              - 한국정보통신진흥협회
      - layout: left
        caption: "2015.04.03"
        description: | 
          - **컴퓨터활용능력 2급**
              - 대한상공회의소
      - layout: left
        caption: "2014.07.31"
        description: | 
          - **ITQ OA Master**(한글액세스, 한글엑셀, 한글파워포인트, 아래한글)
              - 한국생산성본부

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
